accountapp/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from accountapp.views import CustomLoginView, AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView

app_name = "accountapp"

urlpatterns = [
    path('login/', CustomLoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('create/', AccountCreateView.as_view(), name='create'),
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),
]

articleapp/urls.py
from django.urls import path
from django.views.generic import TemplateView

from articleapp.views import ArticleCreateView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView, ArticleListView

app_name = 'articleapp'

urlpatterns = [
    path('list/', ArticleListView.as_view(template_name='articleapp/list.html'), name='list'),
    path('create/', ArticleCreateView.as_view(template_name='articleapp/create.html'), name='create'),
    path('detail/<int:pk>', ArticleDetailView.as_view(template_name='articleapp/detail.html'), name='detail'),
    path('update/<int:pk>', ArticleUpdateView.as_view(template_name='articleapp/update.html'), name='update'),
    path('delete/<int:pk>', ArticleDeleteView.as_view(template_name='articleapp/delete.html'), name='delete'),
]

myPinterest/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from articleapp.views import ArticleListView

urlpatterns = [
    path('', ArticleListView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')),
    path('articles/', include('articleapp.urls')),
    path('comments/', include('commentapp.urls')),
    path('projects/', include('projectapp.urls')),
    path('subscriptions/', include('subscribeapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projectapp/urls.py
from django.urls import path

from projectapp.views import ProjectListView, ProjectCreateView, ProjectDetailView

app_name = 'projectapp'

urlpatterns = [
    path('list/', ProjectListView.as_view(), name='list'),
    path('create/', ProjectCreateView.as_view(), name='create'),
    path('detail/<int:pk>', ProjectDetailView.as_view(), name='detail'),
]

subscribeapp/urls.py
from django.urls import path

from subscribeapp.views import SubscriptionView, SubscriptionListView

app_name = 'subscribeapp'

urlpatterns = [
    path('subscribe/', SubscriptionView.as_view(), name='subscribe'),
    path('list/', SubscriptionListView.as_view(), name='list'),
]

templates/base.html
<!DOCTYPE html>
<html lang="ko">

{% include 'head.html' %}

<body style="font-family:'Roboto Thin',serif; background-color:#F5DEB3">

    {% include 'header.html' %}

    <hr>

    {% block content %}
    {% endblock %}

    <hr>

    {% include 'footer.html' %}

</body>
</html>

templates/footer.html
<div class="footer">
    <div class="footer-buttons">
        <span>Qeustions</span> |
        <span>About</span> |
        <span>News</span> |
    </div>
    <div style="margin-top: 1rem">
        <h6 class="title">rendezvous</h6>
    </div>
</div>

templates/head.html
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width-device-width, initial-scale=1, shrink-to-fit=no">
    <title>Title</title>

{#    Google Material Icons Link    #}
    <link href="https://fonts.googleapis.com/css2?family=Material+Icons" rel="stylesheet">
    
{#    BootStrap Link    #}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    
{#    Google Font Link  #}
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Antonio:wght@100..700&family=Karla:ital,wght@0,200..800;1,200..800&family=Major+Mono+Display&family=Open+Sans:ital,wght@0,300..800;1,300..800&display=swap" rel="stylesheet">

{#    Default CSS Link  #}
    <link rel="stylesheet" type="text/css" href="{%  static 'base.css' %}">
</head>

templates/header.html
<div class="header">
  <div>
    <h1 class="title">rendezvous</h1>
  </div>
  <div class="nav-container">
    <a href="{% url 'articleapp:list' %}" class="nav-link">
      <span>Articles</span>
    </a>
    <a href="{% url 'projectapp:list' %}" class="nav-link">
      <span>Projects</span>
    </a>
    <a href="{% url 'subscribeapp:list' %}" class="nav-link">
      <span>Subscriptions</span>
    </a>
    {% if not user.is_authenticated %}
    <a
      href="{% url 'accountapp:login' %}?next={{ request.path }}"
      class="nav-link"
    >
      <span>Login</span>
    </a>
    <a href="{% url 'accountapp:create' %}" class="nav-link">
      <span>Signup</span>
    </a>
    {% else %}
    <a href="{% url 'accountapp:detail' pk=user.pk %}" class="nav-link">
      <span>MyPage</span>
    </a>
    <form
      action="{% url 'accountapp:logout' %}?next={{ request.path }}"
      method="post"
    >
      {% csrf_token %}
      <button type="submit" class="logout-btn">Logout</button>
    </form>
    {% endif %}
  </div>
</div>